config/routes.rb
Rails.application.routes.draw do
  get '/home',       to: 'static_pages#home'

  resources :users
  resources :rosters
  resources :players
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root to: 'static_pages#home'
end

app/views/layouts/_footer.html.haml
%footer.footer.center
  %small
    Created by
    = link_to 'szp', 'mailto:szpakk@gmail.com'

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-brown.navbar-brown{role: "navigation"}
  .container
    = link_to "53-DBN ROSTER", root_path, id: "logo"
    .navbar-header
      %button.navbar-toggle.collapsed{:type => 'button', "data-toggle" => "collapse", "data-target" => "#bs-example-navbar-collapse-1"}
        %span.sr-only Toggle navigation
        %span.glyphicon.glyphicon-menu-hamburger
    .collapse.navbar-collapse{id: "bs-example-navbar-collapse-1"}
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Projections", rosters_path
        - if admin?
          %li= link_to "Players", players_path
          %li= link_to "Users", users_path
        - if !logged_in?
          %li= link_to "Login",   login_path
          %li= link_to "Sign up", signup_path
        - else
          %li= link_to "Roster", new_roster_path
          %li= link_to "Profile", user_path(current_user)
          %li= link_to "Logout",  logout_path, :method => :delete

app/views/layouts/_shim.html.haml
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title 53-DBN ROSTER
    = csrf_meta_tags
    %meta{name:"viewport", content: "width=device-width, initial-scale=1"}
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    %div.container
      - flash.each do |msg_type, msg|
        = content_tag :div, msg, class: "alert alert-#{msg_type}"
      - flash.clear
      = yield
      = render 'layouts/footer'